### ISSUE TITLE
dist-custom-elements-bundle support in react-output-target

### ISSUE THREAD

**Issue by josephvalexander** [ionic-team/stencil-ds-output-targets#171] opened 2021-08-09 12:24 UTC
react-output-target defines all the custom elements by default, when we use "includeDefineCustomElements" as true. Is there a way to not to define everything at once rather per component so that the distributed react components are tree shakable. Is this supported or what's the easiest way to achieve this?

**Comment by ianldgs** [comment] 2021-09-02 12:32
Duplicate of #142

**Comment by liamdebeasi** [comment] 2021-09-14 13:01
Thanks for the issue. This has been resolved via https://github.com/ionic-team/stencil-ds-output-targets/pull/182 and will be available in an upcoming release of the React output target.

**Closed** 2021-09-14 13:00 UTC
