### ISSUE TITLE
Build is broken since August 2020

### ISSUE THREAD

**Issue by hirsch88** [ionic-team/stencil-ds-output-targets#128] opened 2020-11-08 20:42 UTC
Somehow with the new output for svelte the build is broken.
It requires a `svelte/compile`, but i do not know how we could install that to fix the build.
Or are there any other ideas? happy to help here out.

**Comment by hirsch88** [comment] 2020-11-08 20:43
It is in the file
https://github.com/ionic-team/stencil-ds-output-targets/blob/master/packages/svelte-output-target/src/output-svelte.ts

```typescript
const svelte = require('svelte/compiler');
```

**Comment by gnowland** [comment] 2021-03-10 06:25
Duplicate of https://github.com/ionic-team/stencil-ds-output-targets/issues/121

**Comment by gnowland** [comment] 2021-03-10 06:43
@mihar-22 you worked on this (https://github.com/ionic-team/stencil-ds-output-targets/pull/113) -- would you mind taking a look at this and #121?

To reproduce:
Clone repo, `npm i`, `npm bootstrap`, `npm build` -- fails.

**Comment by gnowland** [comment] 2021-03-10 06:59
My PR #141 appears to fix the issue for me, can you confirm?

**Comment by gnowland** [comment] 2021-03-10 08:17
Fixed this by running `npm install svelte --save-dev` in `component-library`... not sure why that'd be necessary though seeing as `svelte` is a dependency of `@stencil/svelte-output-target`...

**Closed** 2021-05-21 05:52 UTC
