### ISSUE TITLE
Angular Output Target "Cannot Find Module" On Compile

### ISSUE THREAD

**Issue by bellindj** [ionic-team/stencil-ds-output-targets#95] opened 2020-07-17 16:13 UTC
"@stencil/angular-output-target": "^0.0.3"
"@stencil/core": "^1.16.3"

Upgrading angular-output-target from 0.0.2 to 0.0.3, the proxies.ts file now adds an import statement for each component, e.g.:
`import { TabsLabelComponent as ITabsLabelComponent } from '../@meridian/web/dist/types/lib/components/tabs/mds-tabs-label';`

The pathing is not right for my project however, I don't want the "../" at the start of the path. Expected output would be:

`import { TabsLabelComponent as ITabsLabelComponent } from '@meridian/web/dist/types/lib/components/tabs/mds-tabs-label';`

On compile, I get the following error due to the pathing:
```
libs/angular/src/lib/directives/proxies.ts:568:59 - error TS2307: Cannot find module '../@meridian/web/dist/types/lib/components/tabs/mds-tabs-label'.

568 import { TabsLabelComponent as ITabsLabelComponent } from '../@meridian/web/dist/types/lib/components/tabs/mds-tabs-label';
```

Here is my stencil.config.ts blurb for the Angular output target:

```
angularOutputTarget({
      componentCorePackage: '@meridian/web',
      directivesProxyFile: resolve(
        __dirname,
        '../angular/src/lib/directives/proxies.ts'
      ),
      directivesUtilsFile: resolve(
        __dirname,
        '../angular/src/lib/directives/proxies-utils.ts'
      ),
      directivesArrayFile: resolve(
        __dirname,
        '../angular/src/lib/directives/proxies-list.txt'
      ),
      excludeComponents: [],
      valueAccessorConfigs: [],
    }),
```

Is there a way to prevent that relative pathing prefix to be added to the import?

**Comment by LeonardoVizzotto** [comment] 2020-07-17 17:23
Duplicated of #86

**Comment by christian-bromann** [comment] 2024-10-12 00:31
Duplicate of #86

**Closed by christian-bromann** 2024-10-12 00:31 UTC
Labels: triage
