### ISSUE TITLE
bug: React binding output is not tree shakable

### ISSUE THREAD

**Issue by Arvind6353** [ionic-team/stencil-ds-output-targets#292] opened 2021-09-15 12:06 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.8

### Current Behavior

Hi Team,

I am trying to use framework binding with react. 

I used the below config and create a bundle and imported it in a react app as below
```tsx
  reactOutputTarget({
      componentCorePackage: 'fw-design-core',
      proxiesFile: '../react/src/components.ts',
      //loaderDir: 'dist/loader',
      includeDefineCustomElements: true,
    }),


 import { FwButton } from "fw-design-react";

 <div className="App fw-dark-theme">
      {/* <my-component first="first"></my-component> */}
        <FwButton color="primary"
      onFwClick={ e => console.log("event triggerd")}
      >Primary button</FwButton>
    </div>
  );
```
The webcomponent lib holds 2 components my-component and fw-button.

Am using only fw-button in the code. When I run npm run build (create-react-app).

I am seeing many chunk files generated and one of the chunk file related to "my-component" though this is not being used . 

### Expected Behavior

I assume ideally with tree shaking the above chunk file should not be generated since "my-component" is not being used. 

Can you please help with this ?

### Code Reproduction URL

https://github.com/Arvind6353/react-wc/blob/master/src/App.js#L4

@johnjenkins @dmartinjs

**Comment by rwaskiewicz** [comment] 2022-08-29 12:51
I'm going to close this as a duplicate of #255

**Closed by rwaskiewicz** 2022-08-29 12:51 UTC
Labels: triage
