### ISSUE TITLE
[React] bug: SSR output target duplicates the component's internal shadow DOM layout

### ISSUE THREAD

**Issue by dgonzalezr** [ionic-team/stencil-ds-output-targets#470] opened 2024-08-29 18:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.20.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.7.1

### Current Behavior

When using the react output target with SSR inside a Nextjs application, the internal shadow DOM container of the component is rendered twice.

![CleanShot 2024-08-29 at 21 48 56](https://github.com/user-attachments/assets/0df0f74a-3e27-4967-9eb9-510a5d2d06d9)

### Expected Behavior

The internal shadow DOM base container should be rendered only once, as expected, depending on the component layout.

### Steps to Reproduce

Follow the steps described in the **Issue 3** of the reproduction code below

### Code Reproduction URL

https://github.com/dgonzalezr/nx-stencil

**Comment by dgonzalezr** [comment] 2024-08-29 19:54
I can see how the same happens in the [next-app demo of the `stencil-ds-output-target` repo](https://github.com/ionic-team/stencil-ds-output-targets/tree/main/packages/example-project/next-app).

![CleanShot 2024-08-29 at 22 50 24](https://github.com/user-attachments/assets/26e2e9d7-5724-4c12-b339-6bfad113eeef)

**Comment by christian-bromann** [comment] 2024-09-23 17:20
@dgonzalezr thanks for reporting, I am happy to take a look at this.

**Comment by dwirz** [comment] 2024-10-05 14:56
Hey there, unfortunately we encountered the same bug with our components. After some investigation I could pin the problem down to a problem/bug during the Stencil client rehydration. It appears that [`initializeClientHydrate`](https://github.com/ionic-team/stencil/blob/main/src/runtime/client-hydrate.ts#L28) is collecting some nodes and adding them to the `shadowRootNodes` array. These nodes are then appended to the `hostElm.shadowRoot`. [here](https://github.com/ionic-team/stencil/blob/main/src/runtime/client-hydrate.ts#L76) The Problem is that this leads to a duplication of the nodes since they are already part of the `hostElm.shadowRoot` via the slot element and shouldn't be added as a separate node to the `shadowRoot`. For further and visual explanation I created a [Video](https://github.com/user-attachments/assets/9fcba3c6-9ed3-4aa8-839b-e8a182936c9b).

I'd really like to fix the bug within the Stencil repo, but i do not really understand the logic behind the `clientHydrate` function and how/why this function collects the `shadowRootNodes`. Maybe @christian-bromann you know more and you can fix the bug. 😇 

Aside the bug, thanks a lot @christian-bromann for your work! 🎉

**Comment by christian-bromann** [comment] 2024-10-05 16:06
@dwirz I continue to work on improvements on SSR support for React and Vue and I think there is one last issue that you are encountering which can be reproduced if you have multiple layers of components nested into each other. It seems that Next.js wants to serialize each component individually which is problematic for Stencil as it needs to give every component to be hydrated an id, see `s-id` attributes when you look into the source code. We have to make changes in the hydrate script to not always start with `0` on these ids and instead continue with a previous number.

I recommend to use the following two dev builds which contain the most recent fixes:
- `@stencil/react-output-target@0.0.1-dev.11728078825.10143da0`
- `@stencil/core@4.22.0-dev.1728078810.cd53ef7`

**Comment by dwirz** [comment] 2024-10-07 15:02
@christian-bromann I tried to fix the Problem with a little workaround, maybe you can have a look at it and tell me if this is a solution you could go with for the moment. I tested it locally with my project and it worked smoothly. But as stated in the PR it is not the prettiest and most sustainable solution but it would work for the moment. 🙂

**Comment by dwirz** [comment] 2024-10-08 05:17
hey @christian-bromann thanks again for having a look at my PR and directly solving it within Stencil! Your fix https://github.com/ionic-team/stencil/pull/6018 works in our project like a charm! 🥳 hope it gets merged and released soon. 🤞

**Comment by dgonzalezr** [comment] 2024-10-10 17:13
I have tested the most recent version of `@stencil/core` (4.22.1) along with `@stencil/react-output-target` (1.7.1), and it appears that the issue is resolved. @christian-bromann, thank you so much for the hard work 🙌🏼 , I think we can close this issue, and If anything else arises concerning this topic, we can open a new one 🙂 .

**Comment by christian-bromann** [comment] 2024-10-10 17:19
Thanks so much for confirming it works!

**Closed by christian-bromann** 2024-10-10 17:19 UTC
Labels: type: bug
