### ISSUE TITLE
bug: Vue Target compile error with typescript@v4

### ISSUE THREAD

**Issue by ZakaryCode** [ionic-team/stencil-ds-output-targets#305] opened 2022-10-21 07:25 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.18.1

### Stencil Framework Output Target

Vue

### Stencil Framework Output Target Version

0.6.2

### Current Behavior

When using typescript 4+, the defineContainer method will have syntax errors.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/24262362/197136979-943d2355-576e-405e-acab-598fdf024db8.png">

### Expected Behavior

It should be repaired like this.

```diff
export const defineContainer = <Props, VModelType=string|number|boolean>(
  name: string,
  defineCustomElement: any,
  componentProps: string[] = [],
-  modelProp?: string,
+  modelProp = '',
  modelUpdateEvent?: string,
  externalModelUpdateEvent?: string
) => {
```

### Steps to Reproduce

using typescript 4+ target vue lib, then compile with tsc.

### Code Reproduction URL

https://github.com/ionic-team/stencil-ds-output-targets

### Additional Information

-

**Comment by rwaskiewicz** [comment] 2022-10-24 13:39
Hey @ZakaryCode 👋 

Thanks for the report! I'm unable to reproduce this myself when running through the instructions found in https://stenciljs.com/docs/vue. Can you do me a favor and create a minimal reproduction case for the team to pull down and take a look?

Also, can you verify how you're running the build command? That looks to me like output from a terminal window, but it's also possible it's some IDE view (e.g. something in VS Code) that I'm not familiar with. 

Thanks!

**Comment by rwaskiewicz** [comment] 2022-10-24 13:46
Possibly a duplicate of https://github.com/ionic-team/stencil-ds-output-targets/issues/280.

**Comment by rwaskiewicz** [comment] 2022-10-24 14:00
Okay, after playing with this for ~15 minutes or so, I can reproduce this is `strictNullChecks` is set to `true` in the root level `tsconfig.json`. @ZakaryCode is that field set in your `tsconfig`?

**Closed** 2022-10-25 02:27 UTC
Labels: ionitron: needs reproduction
