### ISSUE TITLE
bug: @Event types missing 

### ISSUE THREAD

**Issue by scaljeri** [ionic-team/stencil-ds-output-targets#309] opened 2022-11-10 16:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.19.2

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.4.0

### Current Behavior

So far I had no issues with this stencilJs plugin, but now I've added the following to one of my components

      @Event( { bubbles: false, composed: true } ) treeNodeCheckChanged: EventEmitter<FooEvent>;

Now when I build the angular app, the following error is thrown

    Module '"@web-components/dist/components"' has no exported member 'FooEvent'.

The configuration I added to stencil.config.js is as follows:

     angularOutputTarget({
          componentCorePackage: '@web-components/dist/components',
          directivesProxyFile: './../demo/src/libs/stencil-generated/proxies.ts',
          valueAccessorConfigs: angularValueAccessorBindings,
     }),

Which works without that `@Event` statement!

### Expected Behavior

It should've included the interface `FooEvent` to the proxies.ts file. Inside the proxies.ts files this interface is imported as follows

    import type { FooEvent as IMyComponentFooEvent } from '@web-components/dist/components';

but `FooEvent` is nowhere exported.

### Steps to Reproduce

I've comitted my test setup [here](https://github.com/scaljeri/stenciljs-angular-bug)

The generated files are already generated and included. So to reproduce the error do

    $> cd demo
    $> yarn
    $> yarn build

### Code Reproduction URL

https://github.com/scaljeri/stenciljs-angular-bug

**Comment by sean-perkins** [comment] 2022-11-11 00:18
@scaljeri thanks for this issue.

Custom event types need to be exported from the bundle. Otherwise the output target cannot reference the type. The output target assumes that all referenced types are public and constructs and import statement like:

```
import type { FooEvent } from 'your-library-name';
```

This is why Angular is erroring on build:
> Module '"@web-components/dist/components"' has no exported member 'FooEvent'.

Closing as a duplicate of: #299

If exporting the types does not resolve the issue, let me know and I would be happy to re-open and investigate further.

**Closed by sean-perkins** 2022-11-11 00:18 UTC
Labels: triage

**Comment by scaljeri** [comment] 2022-11-11 07:14
Hi Sean, I tried to export the `FooEvent` too, but it didn't work. However, I'm new to StencilJs, so I probably did something wrong. This is how I exported the model

    ...
    import { FooEvent } from './models';

    export * from './models'; // <-- EXPORT!!

    @Component({
        tag: 'my-component',
        styleUrl: 'my-component.css',
        shadow: true,
     })
     export class MyComponent {
         ...
          @Event( { bubbles: false, composed: true } ) treeNodeCheckChanged: EventEmitter<FooEvent>;

Although I export the model here, it is not compiled into my angular project. Is this what you ment or should it be done differently?
