### ISSUE TITLE
[React] TypeError: head.querySelector is not a function

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil-ds-output-targets#42] opened 2020-04-24 10:08 UTC
When using componentes generated with this plugin in Next.js, server page load throw a TypeError: head.querySelector is not a function because this plugin auto initialize CustomElement even if there is no document or window element.

Related to https://github.com/ionic-team/stencil/issues/2374

**Comment by jthoms1** [comment] 2020-06-18 03:41
Closing this because it is a duplicate of #56. Thanks!

**Closed by jthoms1** 2020-06-18 03:41 UTC
